### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mzanella** [Augugrumi/ghioca#10]
- [ ] lettera facebook
- [ ] caricamento file anonimo
- [ ] togliere filestack
- [ ] abilitare clarify
- [ ] traduzione OCR e tags
- [ ] OCR
- [ ] intro
- [ ] modifica immagini prima di condivisione
- [ ] raccolta dati classificazione (precision e recall)

**Comment by mzanella** [comment]
##  raccolta dati classificazione (precision e recall)
Chiediamo ai nostri beta tester di inviarci le mail così abbiamo immagini + riscontro

**Comment by Polpetta** [comment]
Dobbiamo aggiornare la lista
